### ISSUE TITLE
Spider eyes not packing into blocks

### ISSUE THREAD

**Issue by Justin-Erwin** [BTW-Community/Deco-Addon-2#51]
Also, the block to slab recipe in Craft Guide shows an output of one slab per three blocks. I'm guessing this is not intended. 

Additionally, but possibly intended, there is no way to turn slabs back to blocks directly (though slab --> eyes ---> blocks provides a way once packable again).

**Comment by Justin-Erwin** [comment]
Only slightly related, any plans on Deco changing packing on the other 16 stack size items to require 16 items to pack into blocks instead of 9 like you have done with spider eyes?

**Comment by ammoore00** [comment]
Fixed for next release :)

As for changing the other blocks, probably not. Deco added spider eye blocks so that was not a change from BTW (because the blocks don't exist in BTW). If I was going to change the number to pack it would be done in BTW itself. Haven't really considered it for that, but I can definitely say that won't be something deco does.

**Comment by Justin-Erwin** [comment]
Yeah, I had a brain fart, lol. At first I thought 16 for spider eyes was inconsistent (though I like it) but I forgot that oysters are 16 as well and both are the rarer drops. 

Carry on, nothing to see here :)
